language: rust
rust:
        - stable
        - beta
        - nightly
script:
        - cargo c --verbose
        - cargo b --verbose
        - cargo t --verbose
jobs:
        allow_failures:
                - rust: nightly
        fast_finish: true
cache: cargo
